### ISSUE TITLE
Implement Increment class

### ISSUE THREAD

**Issue by travissluka** [UMD-AOSC/OISSTv3#12]
Implement the Increment class in a similar way to what was done with State. 

I would recommend first creating a common base class, say `Fields` that `State` and `Increment` will both inherit from. Move the `atlasFieldSet_` variable into this class. Then, as you're implementing the members of `Increment`, if the logic is identical to what is in `State`, move the entire member function from `State` to `Fields`... that way you wont' have to write as much duplicate code in `Increment`

**Comment by loganchen39** [comment]
@travissluka If it's ok, for now I'll plan not to implement Fields, but I'll keep this suggestion in mind and will implement it eventually as it makes sense. The reason is that Jim wants to have an initial result (e.g. pictures) as soon as possible, no later than Nov. 15.

**Comment by loganchen39** [comment]
@travissluka After completing class State, my next step will be to implement class Increment, although in your original "class implementation order for JEDI.docx" the next one should be class GetValues. I hope it's ok.

**Comment by travissluka** [comment]
Sounds good. I think they could be done in either order, but Increment is similar to State, so it should probably be more straight forward. First step would be to create the common Fields base class and do a small PR with that

**Comment by loganchen39** [comment]
@travissluka I'm dealing with missing_value/_FillValue, do we have a unified missng_value, e.g. 1.e20? As I checked the JEDI data files, some _FillValue are -3.33476705790481e+38, some are -999., and some NaNf. The problem is our current Atlas version does not support "missing_value" (Although Willem said that in his latest Atlas version it provides support for missing_value, which is 1 or 2-week ago.) So currently I'll have to compare the actual values to determine the missing_values. 

Do you have any suggestions?

**Comment by travissluka** [comment]
> @travissluka I'm dealing with missing_value/_FillValue, do we have a unified missng_value, e.g. 1.e20? As I checked the JEDI data files, some _FillValue are -3.33476705790481e+38, some are -999., and some NaNf. The problem is our current Atlas version does not support "missing_value" (Although Willem said that in his latest Atlas version it provides support for missing_value, which is 1 or 2-week ago.) So currently I'll have to compare the actual values to determine the missing_values.
> 
> Do you have any suggestions?

@loganchen39 Try to keep conversations in their relevant issues (otherwise it can be hard for me to keep up with the dozen or so issues  I see a day), see https://github.com/UMD-AOSC/OISSTv3/issues/13 about the missing value issue. Also, if you are working on that now, please assign yourself on the github issue so that I know that you're working on it and to not look into it myself.  

It is probably best if you do the following:
1. When reading in from a netcdf file and placing in an atlas structure, replace the _FillValue from the netcdf file with the missing values defined here https://github.com/JCSDA-internal/oops/blob/develop/src/oops/util/missingValues.h. These are the missing values that tend to be used throughout JEDI internally
2. when doing any of the `State` or `Increment` math, skip over the values equal to those in missingValues.h
3. When writing out to a netcdf file, you can probably use whatever you want for the netcdf _FillValue, I'm not sure what is being used throughout JEDI, but it's probably inconsistent. So use whatever you want

**Comment by travissluka** [comment]
@loganchen39 also, after this week the JEDI team should be a lot less busy. If there are new features in atlas that you need, we can ask the JEDI folks to update to the latest versions.
