### ISSUE TITLE
Use missing values for land

### ISSUE THREAD

**Issue by travissluka** [UMD-AOSC/OISSTv3#13]
- missing value from netcdf should be read/written
- within the state field, missing values should be stored using the values given in this file https://github.com/JCSDA-internal/oops/blob/develop/src/oops/util/missingValues.h
- math operators should skip over missing values.

for example, the output from the state test looks like this because missing values are not given
![image](https://user-images.githubusercontent.com/12516201/97021629-4ec31580-1510-11eb-86fd-9c8de7f72fd2.png)

**Comment by loganchen39** [comment]
@travissluka Yes I know this issue. I asked Willem about this missing value problem in Atlas, he replied that the Atlas just had support since the latest release last week. I think eventually we'll use Atlas (e.g. Field class) for computation, so we may need to use the latest Atlas version.

**Comment by loganchen39** [comment]
@travissluka  I forgot this thread. will follow the instructions. Thanks.
