### ISSUE TITLE
Implement the hofx_nomodel.x application

### ISSUE THREAD

**Issue by travissluka** [UMD-AOSC/OISSTv3#19]
First real application! 
`hofx_nomodel.x` is responsible for applying the observation operator to a background state given a set of observation locations.

- requires sample observations (#16 )
- requires GetValues implemented (#18 )

**Comment by loganchen39** [comment]
@travissluka For this task, are we supposed to generate the executables of "umdsst_hofx_nomodel.x" whose source file is under "UMD-SST/src/mains/"? In your doc, there're also "hofx.x" and "makeobs.x". Or should I start working on class Covariance?

**Comment by travissluka** [comment]
the executable is already being generated, and _should_  work now. The main thing that needs to be done is to hook up the test output comparison script. I can do that, since it is the first time we'll be using the executables to generate test output that is compared against reference answers. You can hook up the rest of the executable tests in a similar way when the time comes.

We can skip `hofx.x` since we do not have a forecast model currently, so it will not behave any different from `hofx_nomodel.x`.  The next thing you should probably work on is https://github.com/UMD-AOSC/UMD-SST/issues/21

**Comment by loganchen39** [comment]
@travissluka ok, I'll check #21 .
