### ISSUE TITLE
Change "float" to "double" 

### ISSUE THREAD

**Issue by travissluka** [UMD-AOSC/OISSTv3#20]
Interfaces with JEDI typically all assume `double` instead of `float`. I've been warned that there might be problems if we continue using `float`. (as you've seen the tolerances need to be increased quite a bit when using `float`).
Some people on the JEDI team are looking into whether parts of the interface can use `float`, but for safety reasons now we should use `double`.

**Comment by loganchen39** [comment]
@travissluka I have changed float to double within JEDI, but for reading/writing netCDF files I still use float as all of my current files use float internally.

**Comment by travissluka** [comment]
@loganchen39 Don't close issues manually. They get closed when an associated PR gets merged in. Also, when you work on an an issue, please assign your self (a link in the top right of this page) so I know you're working on it and so don't start working in it myself.

**Comment by loganchen39** [comment]
@travissluka Good, just assigned to myself.

**Comment by travissluka** [comment]
@loganchen39 If you have this one done, can you issue a PR for it? I would like to have it in before I do  https://github.com/UMD-AOSC/OISSTv3/issues/23
