### ISSUE TITLE
Implement the LinearGetValues class

### ISSUE THREAD

**Issue by travissluka** [UMD-AOSC/OISSTv3#21]
Similar to `GetValues` except it operates on `Increment` and so performs the tangent linear / adjoint for interpolation.
`TestLinearGetValues` should pass after this

`GetValues` is probably easier, so that one should be done first.

**Comment by travissluka** [comment]
This will be very similar to `GetValues`. Major difference is that in addition to the forward interpolation (the setTrajectory and TL part) which will be the same as `GetValues`, we will also have the backward interpolation (AD part) which will use the `apply_ad` operator of the interpolation routines provided by oops.

**Comment by loganchen39** [comment]
@travissluka ok, Let me check.
