### ISSUE TITLE
Implement the Covariance class

### ISSUE THREAD

**Issue by loganchen39** [UMD-AOSC/OISSTv3#30]
I'll starting working on the Covariance class.

**Comment by travissluka** [comment]
@loganchen39 hold off on this for now. I need to go through in my head first the steps that need to be accomplished. There will be quite a few steps. We might have to do a small bit of Forrtan/C++ interface code similar to what was needed by `GetValues`

**Comment by loganchen39** [comment]
@travissluka ok, let me know the steps and let me implement them so I can get familiar. I'm free now. I'll also take a look at the code.

**Comment by travissluka** [comment]
I'm closing this and opening up multiple issues for the individual steps
