### ISSUE TITLE
Convert background to/from Celsius

### ISSUE THREAD

**Issue by travissluka** [UMD-AOSC/OISSTv3#33]
SST observations within JEDI are currently in Celsius, but our model state here is in Kelvin. We need to either 

1) convert the state between K and C when reading/writing the state or
2) Convert between K and C within `GetValues`.

1 might be more convenient, especially if we plan on using the CoolSkin observation operator, which I think currently expects the get the GeoVaLs as Celsius.

**Comment by loganchen39** [comment]
@travissluka Check the Pull Request #41, I used your 1st method: convert the state between K and C when reading/writing the state.
