### ISSUE TITLE
add a mask field to Geometry class

### ISSUE THREAD

**Issue by travissluka** [UMD-AOSC/OISSTv3#38]
on creation `Geometry` should read in a land mask from a file (separate from what is being done in `State` now), specified by the yaml configuration and save the mask in an atlas field contained in `Geometry`

**Comment by travissluka** [comment]
if the mask is loaded and saved to `Geometry::atlasFieldSet_` in the Geometry constructor, adding it as an integer field with the field name "gmask", them BUMP should be able to do land masking if
```yaml
mask_check: 1
network: 1
```
is added to the bump section of `staticbinit.yml`

**Comment by loganchen39** [comment]
@travissluka I'm working on this issue. How are supposed to get this land mask file? Are we supposed to produce this file ourselves with respect to the 1x1 degree background grid, or is there already such a file?

**Comment by travissluka** [comment]
yes, I would just create a new file with a 1 or 0 mask value based on the the current 1x1 background file we're using.

**Comment by loganchen39** [comment]
Ok, I'll create such mask file.
