### ISSUE TITLE
JEDI test for 0.25x0.25 grid

### ISSUE THREAD

**Issue by loganchen39** [UMD-AOSC/OISSTv3#72]
@travissluka  I reproduced your initial JEDI test, it's pretty fast on Cheyenne, taking about 5 minutes with 1 node (36 processors) to finished 1 month run.

Now I'll try to test for 0.25x0.25 grid, I've uploaded the initial background file "20080101_regridded_sst.nc" and the landmask.nc files at my feature/test branch. Please help check if they are ok when you get a minute.

**Comment by travissluka** [comment]
@loganchen39 Can you create a PR merging your 1/4 degree landmask and background files? I would like to have those as part of the repository before we get too far into doing experiments. (and perhaps rename the files so we know clearly which ones are 1/4 deg and which ones are 1 deg)
